title: My Page
author: janie-debug54
email:
description: > # this means to ignore newlines until "baseurl:"
  Total newbie at coding: Watch this train wreck of a coder get hopefully-maybe better! Comments are always encouraged. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
